# API Testing
GET https://backend-rama-73763759634.us-central1.run.app/ HTTP/1.1

###
# GET : All Notes
GET https://backend-rama-73763759634.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# GET : Note by ID
GET https://backend-rama-73763759634.us-central1.run.app/api/v1/notes/4 HTTP/1.1
Content-Type: application/json

###
# POST : Create Note
POST https://backend-rama-73763759634.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Note baru",
  "isi": "Ini adalah isi dari note baru"
}

###
# PUT : Update Note
PUT https://backend-rama-73763759634.us-central1.run.app/api/v1/notes/4 HTTP/1.1
Content-Type: application/json

{
  "judul": "Note 4 Updated",
  "isi": "Ini adalah isi dari note 4 yang sudah diperbarui"
}

###
# DELETE : Delete Note
DELETE https://backend-rama-73763759634.us-central1.run.app/api/v1/notes/5 HTTP/1.1
Content-Type: application/json


